version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: geometry_sme_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - geometry_sme_network

  redis:
    image: redis:7-alpine
    container_name: geometry_sme_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - geometry_sme_network

volumes:
  es_data:
  redis_data:

networks:
  geometry_sme_network:
    driver: bridge